swagger: '2.0'
info:
  version: 1.0.0
  title: get-user-info
  description: Returns user info from Grouper and LDAP
host: localhost:8080
basePath: "/function"
paths:
  /get-user-info:
    post:
      summary: Returns user info from Grouper and LDAP
      description: Returns user info from Grouper and LDAP
      parameters:
        - in: body
          name: username
          schema:
            type: object
            properties:
              username:
                type: string
                example: "username"
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              id:
                type: string
                example: "username"
              name:
                type: string
                example: first last
              first_name:
                type: string
                example: first
              last_name:
                type: string
                example: last
              email:
                type: string
                example: first.last@cyverse.fake.wut
              institution:
                type: string
              source_id:
                type: string